---
name: Build Nightly (Docker)

on:
  workflow_dispatch:
  
  schedule:
  - cron: '45 22 * * 5' # https://crontab.guru/

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_GITHUB_IMAGE: ${{ github.repository }}
  REGISTRY_DOCKERHUB: registry.hub.docker.com
  REGISTRY_DOCKERHUB_IMAGE: kdsda/nomad-pack

jobs:
  docker-build-nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        image:
        - alpine
        version:
        - 0.0.1-techpreview.4

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Get date
      id: timestamp
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=week::$(date +'%Y.%V')"
    -
      name: Login to GitHub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Login to Docker Hub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_DOCKERHUB }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY_GITHUB }}/${{ env.REGISTRY_GITHUB_IMAGE }}
          ${{ env.REGISTRY_DOCKERHUB }}/${{ env.REGISTRY_DOCKERHUB_IMAGE }}
        flavor: |
          latest=false
          prefix=${{ matrix.image }}-,onlatest=false
          suffix=-prerelease
        tags: |
          type=raw,value=${{ matrix.version }}-${{ steps.timestamp.outputs.week }}
          type=raw,value=${{ matrix.version }}
        labels: |
          org.opencontainers.image.title='Nomad-Pack'
          org.opencontainers.image.description='Nomad-Pack Container Image'
          org.opencontainers.image.authors='Kreditorforeningen'
          org.opencontainers.image.vendor='Kreditorforeningen'
          org.opencontainers.image.url='https://github.com/hashicorp/nomad-pack'
          org.opencontainers.image.documentation='https://github.com/Kreditorforeningens-Driftssentral-DA/container-image-nomad-pack/blob/main/README.md'
          org.opencontainers.image.source='https://github.com/Kreditorforeningens-Driftssentral-DA/container-image-nomad-pack'
          org.opencontainers.image.created="${{ steps.timestamp.outputs.date }}"
          org.opencontainers.image.version="${{ matrix.version }}"
          org.opencontainers.image.base.name="${{ matrix.image }}"
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: "Dockerfile.nightly.${{ matrix.image }}"
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        build-args: |
          PRE_RELEASE=yes
          NOMAD_PACK_VERSION=${{ matrix.version }}
