---
name: Build (Docker)

on:
  workflow_dispatch:
  
  schedule:
  - cron: '15 0 15 * *' # https://crontab.guru/

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_GITHUB_IMAGE: ${{ github.repository }}
  REGISTRY_DOCKERHUB: registry.hub.docker.com
  REGISTRY_DOCKERHUB_IMAGE: kdsda/nomad-pack

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      packages: write
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        image:
        - alpine
        - debian
        version:
        - 0.0.1-techpreview1

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Get date
      id: timestamp
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=week::$(date +'%Y.%V')"
    -
      name: Login to GitHub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Login to Docker Hub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_DOCKERHUB }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY_GITHUB }}/${{ env.REGISTRY_GITHUB_IMAGE }}
          ${{ env.REGISTRY_DOCKERHUB }}/${{ env.REGISTRY_DOCKERHUB_IMAGE }}
        flavor: |
          latest=auto
          prefix=${{ matrix.image }}-,onlatest=true
        tags: |
          type=raw,value=${{ matrix.version }}-${{ steps.timestamp.outputs.week }}
          type=raw,value=${{ matrix.version }}
        labels: |
          org.opencontainers.image.title='nomad-pack'
          org.opencontainers.image.description='Rendering HashiCorp Nomad job-templates'
          org.opencontainers.image.vendor='Kreditorforeningen'
          org.opencontainers.image.authors='drift@kred.no'
          org.opencontainers.image.source='https://github.com/Kreditorforeningens-Driftssentral-DA/container-image-nomad-pack'
          org.opencontainers.image.created="${{ steps.timestamp.outputs.date }}"
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: "Dockerfile.${{ matrix.image }}"
        tags: ${{ steps.meta.outputs.tags }}
        push: true
        #push: false
        build-args: |
          NOMAD_PACK_VERSION=${{ matrix.version }}
